[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "unstract-adapters"
version = "0.5.0"
description = "Unstract Adapters"
authors = [
    {name = "Zipstack Inc.", email = "devsupport@zipstack.com"},
]
dependencies = [
        "llama-index==0.10.16",
        "llama-index-embeddings-google==0.1.3",
        "llama-index-embeddings-azure-openai==0.1.6",
        "llama-index-embeddings-fastembed==0.1.4",
        "llama-index-embeddings-openai==0.1.6",
        "llama-index-embeddings-huggingface==0.1.4",
        "llama-index-embeddings-azure-openai==0.1.6",
        "llama-index-vector-stores-postgres==0.1.2",
#        "llama-index-vector-stores-supabase==0.1.3",
        "llama-index-vector-stores-milvus==0.1.4",
        "llama-index-vector-stores-weaviate==0.1.3",
        "llama-index-vector-stores-pinecone==0.1.4",
        "llama-index-vector-stores-qdrant==0.1.3",
        "llama-index-llms-palm==0.1.3",
        "llama-index-llms-mistralai==0.1.4",
        "llama-index-llms-anyscale==0.1.3",
        "llama-index-llms-anthropic==0.1.5",
        "llama-index-llms-openai==0.1.7",
        "llama-index-llms-vertex==0.1.4",
        "llama-index-llms-replicate==0.1.3",
]
requires-python = ">=3.9,<3.12"
readme = "README.md"
classifiers = [
  "Programming Language :: Python"
]
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
lint = [
    "autopep8~=2.0.2",
    "black~=23.3.0",
    "docutils~=0.20.1",
    "flake8~=6.0.0",
    "flake8-pyproject~=1.2.2",
    "isort~=5.12.0",
    "pre-commit~=3.3.1",
    "yamllint>=1.35.1",
    "mypy~=1.2.0",
    "absolufy-imports~=0.3.1",
    "types-requests~=2.31.0.6",
    "types-redis~=4.6.0.3",
    "types-PyYAML~=6.0.12.12",
    "types-pyOpenSSL~=23.2.0.2",
    "types-PyMySQL~=1.1.0.1",
    "types-tzlocal~=5.1.0.1",
]

[tool.black]
line-length = 80
target-version = ['py39']

[tool.pycln]
all = true

[tool.pyupgrade]
keep_dict_typing = true

[tool.flake8]
max-line-length = 80
exclude = "pyproject.toml"

[tool.isort]
line_length = 80
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
profile = "black"

# IMPORTANT!
# Keep this same as mypy hook args in .pre-commit-config.yaml
[tool.mypy]
allow_subclassing_any = true
allow_untyped_decorators = true
check_untyped_defs = true
exclude = '''(?x)^(
    __pypackages__/.*|
)$'''
follow_imports = "silent"
ignore_missing_imports = true
implicit_reexport = true
pretty = true
python_version = "3.9"
show_column_numbers = true
show_error_codes = true
strict = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pdm.build]
includes = ["src"]
package-dir = "src"
# source-includes = ["tests"]
