[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
name = "unstract-adapters"
version = "0.3.0"
description = "Unstract Adapters"
authors = [
    {name = "Zipstack Inc.", email = "devsupport@zipstack.com"},
]
dependencies = [
        "llama-index==0.9.28",
        # OpenAI Embedding & LLM
        "openai==1.3.9",
        # Google PaLM Embedding & LLM
        "google-generativeai==0.3.1",
        # vertex ai
        "google-cloud-aiplatform==1.40.0",
        # Embeddings
        "fastembed==0.1.3",
        "huggingface==0.0.1",
        # VectorDBs
        "pymilvus==2.3.4",
        #Required by Supabase
        "vecs==0.1.0",
        "flupy==1.2.0",
        #vecs=0.1.0 can only use pgvector==0.1.*
        "pgvector==0.1.*",
        "pinecone-client==2.2.4",
        "psycopg2-binary==2.9.9",
        "qdrant-client==1.7.0",
        "supabase==2.2.1",
        "weaviate-client==3.25.3",
        #Required by postgres
        "asyncpg==0.29.0",
        "SQLAlchemy==2.0.26",
        # LLM
        "anthropic==0.7.8",
        "replicate==0.22.0",
        "anyscale==0.5.165",
        "mistralai==0.0.8",
]
requires-python = ">=3.9,<3.12"
readme = "README.md"
classifiers = [
  "Programming Language :: Python"
]
license = {text = "MIT"}

[tool.pdm.dev-dependencies]
lint = [
    "autopep8~=2.0.2",
    "black~=23.3.0",
    "docutils~=0.20.1",
    "flake8~=6.0.0",
    "flake8-pyproject~=1.2.2",
    "isort~=5.12.0",
    "pre-commit~=3.3.1",
    "yamllint>=1.35.1",
    "mypy~=1.2.0",
    "absolufy-imports~=0.3.1",
    "types-requests~=2.31.0.6",
    "types-redis~=4.6.0.3",
    "types-PyYAML~=6.0.12.12",
    "types-pyOpenSSL~=23.2.0.2",
    "types-PyMySQL~=1.1.0.1",
    "types-tzlocal~=5.1.0.1",
]

[tool.pdm.build]
includes = ["src"]
package-dir = "src"
# source-includes = ["tests"]
